home/urls.py
from django.urls import path, re_path
from .views import HomeView, JobView, ContactView, OrderView, OrderCompleteView
from .views import (
    ServicesView,
    LabiExpoView,
    LabiBrandingView,
    LabiPrintView,
    LabiDesignView,
)
from django.views.generic import TemplateView

app_name = "home"

urlpatterns = [
    path("", HomeView.as_view(), name="index"),
    path("contact", ContactView.as_view(), name="contact"),
    path("job", JobView.as_view(), name="job"),
    path("order", OrderView.as_view(), name="order"),
    path("order_complete", OrderCompleteView.as_view(), name="order_complete"),
    path("services", ServicesView.as_view(), name="services"),
    path("labi_print", LabiPrintView.as_view(), name="labi_print"),
    path("labi_design", LabiDesignView.as_view(), name="labi_design"),
    path("labi_expo", LabiExpoView.as_view(), name="labi_expo"),
    path("labi_branding", LabiBrandingView.as_view(), name="labi_branding"),
    re_path(
        r"^robot\.txt$",
        TemplateView.as_view(
            template_name="home/robots.txt", content_type="text/plain"
        ),
    ),
]

labi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404

urlpatterns = [path("admin/", admin.site.urls), path("", include("home.urls"))]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "home.views.page_not_found_view"

home/models.py
from django.db import models
import uuid


class Job(models.Model):
    name = models.CharField(verbose_name="Name", max_length=100, blank=False)
    phone = models.CharField(verbose_name="Phone", max_length=10, blank=False)
    email = models.EmailField(verbose_name="Email", max_length=50, blank=False)
    text = models.TextField(verbose_name="Comment", max_length=300, blank=False)

    def __str__(self) -> str:
        return f"{self.name}"


def file_upload_path(instance, filename):
    return f"order_files/{filename}"


class Order(models.Model):
    client = models.CharField(verbose_name="Client", max_length=100, blank=False)
    phone = models.CharField(verbose_name="Phone", max_length=10, blank=False)
    email = models.EmailField(verbose_name="Email", max_length=50, blank=False)
    order = models.TextField(verbose_name="Order comment", max_length=300, blank=False)
    order_number = models.CharField(
        verbose_name="Order Number", max_length=20, unique=True, blank=False
    )
    file_upload = models.FileField(
        verbose_name="File Upload", upload_to="order_files/", blank=True, null=True
    )

    def __str__(self) -> str:
        return f"{self.client}"

    def generate_order_number(self):
        return str(uuid.uuid4().hex[:10])

    def save(self, *args, **kwargs):
        if not self.order_number:
            self.order_number = self.generate_order_number()
        super().save(*args, **kwargs)

home/forms.py
from django import forms

from .models import Job, Order


class JobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = ["name", "phone", "email", "text"]


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["client", "phone", "email", "order", "file_upload"]

home/views.py
from django.views.generic import CreateView, TemplateView
from .models import Job, Order
from .forms import JobForm, OrderForm
from django.shortcuts import render


class HomeView(TemplateView):
    template_name = "home/index.html"


class JobView(CreateView):
    model = Job
    form_class = JobForm
    template_name = "home/index.html"
    success_url = "order_complete"


class ContactView(TemplateView):
    template_name = "home/contact.html"


class OrderView(CreateView):
    model = Order
    form_class = OrderForm
    template_name = "home/order.html"
    success_url = "order_complete"


class OrderCompleteView(TemplateView):
    template_name = "home/order_complete.html"


class ServicesView(TemplateView):
    template_name = "home/services.html"


class LabiPrintView(TemplateView):
    template_name = "home/print.html"


class LabiExpoView(TemplateView):
    template_name = "home/expo.html"


class LabiDesignView(TemplateView):
    template_name = "home/design.html"


class LabiBrandingView(TemplateView):
    template_name = "home/branding.html"


def page_not_found_view(request, exception):
    return render(request, "home/errors/404.html", status=404)

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Labi Agency - Рекламное агенство с большим набором услуг</title>
    <meta name="description" content="ЛАБИ — значит «хорошо». Именно так мы делаем нашу работу. Качественно и ответственно. По всем вопросам обращаться +7 921 366 04 32 г. Санкт-Петербург"/>
    <meta name="keywords" content="рекламное, агенство, выставки, типография, дизайн, брендирование, реклама, оформление помещений, внешняя реклама, создание логотипов, сувениры"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Lato:500" rel="stylesheet">
    <style>
        .nav-logo {
            display: flex;
            align-items: center;
            margin-left: 20px;
            margin-top: 20px;
        }

        .social {
            display: flex;
        }

        .social a {
            text-decoration: none;
        }

        .nav-wrapper{
            width: 100%;
            height: auto;
            position: -webkit-sticky;
            background-color: #fff;
        }
        .nav-bar img{
            height: 70%;
            width: auto;
            justify-self: start;
            margin-left: 20px;
            margin-top: 20px;
        }

        .nav-logo figure:hover img {
            opacity: 1;
            -webkit-animation: flash 1.5s;
            animation: flash 1.5s;
        }
        @-webkit-keyframes flash {
            0% {
                opacity: .4;
            }
            100% {
                opacity: 1;
            }
        }
        @keyframes flash {
            0% {
                opacity: .4;
            }
            100% {
                opacity: 1;
            }
        }

        .nav-menu{
            font-family: "Lato", serif;
            font-size: 18px;
            text-transform: uppercase;
            margin-top: -50px;
            padding-right: 20px;
        }

        .nav-bar ul{
            display: flex;
            flex-direction: row;
            justify-content: end;
            width: 100%;
            gap: 10px;
        }

        .nav-bar li{
            list-style-type: none;
            position: relative;
        }

        .nav-bar a{
            display: block;
            text-decoration: none;
            color: #8a0e0d;
        }

        .nav-bar a:hover{
            color: #0c265d;
        }

        .nav-bar li ul{
            display: none;
            position: absolute;
            height: auto;
            width: auto;
            margin: 0;
            padding: 10px;
            background-color: #f9f9f9;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        }

        .nav-bar li:hover ul{
            display: block;
        }

        .content-page{
            margin-top: 50px;
        }

        .social{
            display: flex;
            margin-top: -100px;
        }
    </style>
</head>
<body>
    <div class="nav-wrapper">
        <div class="nav-bar">
            <div class="nav-logo">
                <figure><img src="https://labi.agency/wp-content/themes/labi-agency-theme/assets/img/logo-colored.svg" alt="Labi"></figure>
                <div class="social" style="margin-top: 10px; margin-left: 50px">
                    <a href="https://api.whatsapp.com/send/?phone=%2B79213660432&text&type=phone_number&app_absent=0"><img src="https://labi.agency/wp-content/themes/labi-agency-theme/assets/img/whatsapp.svg" alt="WhatsApp"></a>
                    <a href="https://t.me/AndreiBalchugov_reklama"><img src="https://labi.agency/wp-content/themes/labi-agency-theme/assets/img/tg.svg" alt="Telegram"></a>
                </div>
            </div>
            <ul class="nav-menu">
                <li class="nav-item"><a href="{% url 'home:index' %}">Главная</a></li>
                <li class="nav-item">
                    <a href="{% url 'home:services' %}">Услуги</a>
                    <ul>
                        <li><a href="{% url 'home:labi_print' %}">ТИПОГРАФИЯ</a></li>
                        <li><a href="{% url 'home:labi_expo' %}">ВЫСТАВКИ</a></li>
                        <li><a href="{% url 'home:labi_design' %}">ДИЗАЙН</a></li>
                        <li><a href="{% url 'home:labi_branding' %}">ПРОИЗВОДСТВО</a></li>
                    </ul>
                </li>
                <li class="nav-item"><a href="{% url 'home:order' %}">Заказать</a></li>
                <li class="nav-item"><a href="{% url 'home:contact' %}">Контакты</a></li>
            </ul>
        </div>
    </div>
    <div class="content-page">
        {% block content %}
        {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

home/templates/home/design.html
{% extends "home/base.html" %}

{% block content %}
<style>
        .work-examples {
            margin-top: 10%;
            display: flex;
            flex-wrap: wrap;
            gap: 1%;
            justify-content: center;
        }

        .work-example {
            width: 500px;
            margin-bottom: 20px;
            text-align: center;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            padding: 10px;
        }

        .work-example img {
            max-width: 100%;
            height: 300px;
            object-fit: cover;
        }

        .order-button {
            background-color: #0c265d;
            color: #fff;
            padding: 5px 10px;
            text-decoration: none;
            display: inline-block;
            margin-top: 10px;
        }

        .order-button:hover{
            background-color: #8a0e0d;
        }
    </style>
    <div class="work-examples">
        <div class="work-example">
            <img src="https://sun27-2.userapi.com/impg/47nw2nVVKZ498T5zL4KJVDLkd9zuGdB6evWPaw/roDBpb1n5kU.jpg?size=1200x360&quality=96&sign=11ef74745685e51a4e14a63e613d634b" alt="пример">
            <a class="order-button" href="{% url 'home:order' %}">Заказать</a>
        </div>
        <div class="work-example">
            <img src="https://sun27-1.userapi.com/impg/s6BGFpZ-UjZJ2fYqWMRJQXQ-nrI2H0VtZzFEqA/df6lt5W_8Vk.jpg?size=1000x662&quality=96&sign=df849993e7e96fd5073995b4a8ddbb3f" alt="пример">
            <a class="order-button" href="{% url 'home:order' %}">Заказать</a>
        </div>
        <div class="work-example">
            <img src="https://sun9-9.userapi.com/impg/GLnZ1xFQrzqYyqyxnynwAMjZSvT4WIAWLhT9EQ/_S8AOa6dgIs.jpg?size=1262x710&quality=96&sign=6b2569af161d05e57cc759c83fae1a4d" alt="пример">
            <a class="order-button" href="{% url 'home:order' %}">Заказать</a>
        </div>
        <div class="work-example">
            <img src="https://sun9-3.userapi.com/impg/Z4zDG9ocm-ODgwAqo6V9ZEtzfoHldbGaCKOl5A/FUtLjvLmohU.jpg?size=1500x902&quality=96&sign=a49a32e90b899e66dbaa12ee77d01108" alt="пример">
            <a class="order-button" href="{% url 'home:order' %}">Заказать</a>
        </div>
        <div class="work-example">
            <img src="https://sun9-50.userapi.com/impg/gT6YrC-ZcT7CCLUNVgmOWmMv1qlKgLEC1KHunw/dFvcbfr2aNY.jpg?size=1152x768&quality=96&sign=7f784a0d0b0ad79c7a9e79ac3a2fb709" alt="пример">
            <a class="order-button" href="{% url 'home:order' %}">Заказать</a>
        </div>
        <div class="work-example">
            <img src="https://sun9-50.userapi.com/impg/Ishemef-xNCXsKknETxB58ujzIHfIvA2dnHiRQ/3DKJL_ICuso.jpg?size=1000x628&quality=96&sign=97b1aa43effffc137bfcda3e43209c52" alt="пример">
            <a class="order-button" href="{% url 'home:order' %}">Заказать</a>
        </div>
        <div class="work-example">
            <img src="https://sun9-47.userapi.com/impg/xqCRTNBciTkMhx66n9nBNLxKolg0JCrq-7z6VQ/EBeS1LuaDuc.jpg?size=800x600&quality=96&sign=b80cf98edfc4b4b39098aa0e963abbc5" alt="пример">
            <a class="order-button" href="{% url 'home:order' %}">Заказать</a>
        </div>
    </div>
{% endblock content %}

home/templates/home/index.html
{% extends "home/base.html" %}

{% block content %}
    <style>
        .banner img{
            width: 100%;
            padding: 10px;
        }

        .banners-slider{
            max-width: 70%;
            margin: 0 auto;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            margin-top: 20px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        }

        .dot{
          height: 15px;
          width: 15px;
          margin: 0 2px;
          background-color: #0c265d;
          border-radius: 50%;
          display: inline-block;
          transition: background-color 0.6s ease;
        }

        .fade {
          animation-name: fade;
          animation-duration: 1.5s;
        }

        .active {
          background-color: #8a0e0d;
        }

        .labi{
            text-align: center;
            font-family: "Lato", serif;
            font-weight: bold;
            font-size: 28px;
            margin-top: 100px;
        }
        @keyframes fade {
          from {opacity: .4}
          to {opacity: 1}
        }

        .form{
            width:35%;
            height:400px;
            background: white;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            padding:20px 30px;
            max-width:calc(100vw - 40px);
            box-sizing:border-box;
            font-family: "Lato", serif;
            position:relative;
            margin-left: 55%;
            margin-top: -380px;
        }

        .job-title h2{
            margin:10px 0;
            padding-bottom:10px;
            width:180px;
            color: black;
            border-bottom:3px solid #78788c
        }

        input{
            width:100%;
            padding:10px;
            box-sizing:border-box;
            background:none;
            outline:none;
            resize:none;
            border:0;
            font-family: "Lato", serif;
            transition:all .3s;
            border-bottom:2px solid #0c265d
        }

        input:focus{
            border-bottom:2px solid #8a0e0d
        }

        p:before{
            content:attr(type);
            display:block;
            margin:28px 0 0;
            font-size:14px;
            color:#5a5a5a
        }

        .job-btn{
            float:right;
            padding:8px 12px;
            margin-top: 30px;
            font-family: "Lato", serif;
            border:2px solid #8a0e0d;
            background:0;
            color:#8a0e0d;
            cursor:pointer;
            transition:all .3s
        }

        .job-btn:hover{
            background:#8a0e0d;
            color:#fff
        }

        .job-contact{
            position:absolute;
            bottom:-15px;
            right:-20px;
            background:#0c265d;
            color:#fff;
            width:320px;
            padding:16px 4px 16px 0;
            font-size:13px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        }

        .form label{
            width: 100%;
        }

        .fa-envelope-o{
            margin-right: 30px;
        }

        .fa{
            font-family: "Lato", serif;
            padding: 10px;
        }

        .about{
            font-family: "Lato", serif;
            font-size: 25px;
            margin-left: 5%;
            width: 40%;
            height: auto;
            margin-top: 10%;
        }

        .about p{
            margin-top: 10px;
            text-align: justify;
        }

        .about-link a{
            font-family: "Lato", serif;
            border:2px solid #0c265d;
            color:#0c265d;
            text-decoration: none;
            padding: 10px;
        }

        .about-link a:hover{
            background:#0c265d;
            color:#fff;
        }
        
        .clients{
            overflow: hidden;
            position: relative;
            width: 100%;
            height: 30%;
        }
        
        .clients-slider{
            display: flex;
            animation: slide 10s linear infinite alternate;
            width: fit-content;
        }
        
        .clients-banner{
            flex: 0 0 auto;
            margin-right: 10px;
        }
        
        .clients-banner img{
            max-width: 30%;
            height: auto;
        }
        
        @keyframes slide {
          0% {
            transform: translateX(0);
          }
          100% {
            transform: translateX(calc(-100% * (var(--count, 0) + 1)));
          }
        }

        .work-examples {
            margin-top: 10%;
            display: flex;
            flex-wrap: wrap;
            gap: 1%;
            justify-content: center;
        }

        .work-example {
            width: 300px;
            margin-bottom: 20px;
            text-align: center;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            padding: 10px;
        }

        .work-example img {
            max-width: 100%;
            height: 300px;
            object-fit: cover;
        }

        .order-button {
            background-color: #0c265d;
            color: #fff;
            padding: 5px 10px;
            text-decoration: none;
            display: inline-block;
            margin-top: 10px;
        }

        .order-button:hover{
            background-color: #8a0e0d;
        }

        footer{
            background-color: #333;
            color: #fff;
            padding: 20px;
            text-align: center;
            margin-top: 20px;
        }

        .footer-container{
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .contact-info p{
            margin: 0;
        }

        .privacy-policy a{
            color: #fff;
            text-decoration: none;
        }
        .privacy-policy a:hover{
            color: #8a0e0d;
            text-decoration: none;
        }

        .copyright{
            margin-top: 20px;
        }

    </style>
    <p class="labi"><b style="color: #8a0e0d">LA</b><b style="color: #0c265d">BI</b> - рекламно-производственная компания и комплексное рекламное агентство</p>
    <div class="banners-slider">
        <div class="banner fade">
            <img src="https://labi.agency/wp-content/uploads/2022/09/blue@2x.jpg">
        </div>
        <div class="banner fade">
            <img src="https://labi.agency/wp-content/uploads/2022/09/red1@2x.jpg">
        </div>
        <div style="text-align:center">
            <span class="dot"></span>
            <span class="dot"></span>
        </div>
    </div>

        <div class="about">
            <p>ЛАБИ — значит «хорошо». Именно так мы делаем нашу работу. Качественно и ответственно.</p>
            <p>А ещё это искусный и умелый.</p>
            <p>И ещё это можно перевести, как удачный. Именно такой выбор
вы сделаете, начав сотрудничество с LABI agency.</p>
            <div class="about-link">
                <a href="{% url 'home:order' %}">Сделать заказ</a>
            </div>
        </div>
        <form method="post" action="{% url 'home:job' %}" class="form">
            {% csrf_token %}
            <h2 class="job-title">ХОЧУ РАБОТАТЬ</h2>
            <label for="id_name"><input type="text" id="id_name" name="name" placeholder="Ваше имя"></label>
            <label for="id_phone"><input type="text" id="id_phone" name="phone" placeholder="Номер телефона"></label>
            <label for="id_email"><input type="email" id="id_email" name="email" placeholder="Адрес электронной почты"></label>
            <label for="id_text"><input type="text" id="id_text" name="text" placeholder="Комментарий (желаемая должность и т.д.)"></label>
            <button class="job-btn" type="submit">Отправить заявку</button>
            <div class="job-contact">
                <span class="fa fa-phone">☎ +7 921 366 04 32</span>
                <span class="fa fa-envelope-o">✉ welcome@labi.agency</span>
            </div>
        </form>

    <div class="work-examples">
        <div class="work-example">
            <h3>ВЫСТАВКИ</h3>
            <img src="https://labi.agency/wp-content/uploads/2021/12/img_3469-scaled.jpg" alt="выставки">
            <a class="order-button" href="{% url 'home:order' %}">Заказать</a>
        </div>
        <div class="work-example">
            <h3>ТИПОГРАФИЯ</h3>
            <img src="https://labi.agency/wp-content/uploads/2021/11/screenshot_4.jpg" alt="типография">
            <a class="order-button" href="{% url 'home:order' %}">Заказать</a>
        </div>
        <div class="work-example">
            <h3>ПРОИЗВОДСТВО</h3>
            <img src="https://labi.agency/wp-content/uploads/2021/12/img_20211206_212140-scaled.jpg" alt="производство">
            <a class="order-button" href="{% url 'home:order' %}">Заказать</a>
        </div>
        <div class="work-example">
            <h3>ДИЗАЙН</h3>
            <img src="https://labi.agency/wp-content/uploads/2021/12/img-20211119-wa0010.jpg" alt="дизайн">
            <a class="order-button" href="{% url 'home:order' %}">Заказать</a>
        </div>
    </div>

    <div class="clients">
        <h2 style="text-align: center; padding-top: 5%">Нам доверяют:</h2>
        <div class="clients-slider">
            <div class="clients-banner"><img src="https://static.tildacdn.com/tild3934-6336-4831-b533-363762343939/opera2.png" alt="Client1"></div>
            <div class="clients-banner"><img src="https://static.tildacdn.com/tild3236-3237-4566-a365-323665383664/photo.png" alt="Client2"></div>
            <div class="clients-banner"><img src="https://static.tildacdn.com/tild6135-6264-4536-b734-373461646130/_.png" alt="Client3"></div>
            <div class="clients-banner"><img src="https://static.tildacdn.com/tild3733-6237-4030-b234-326335616332/photo.png" alt="Client4"></div>
            <div class="clients-banner"><img src="https://static.tildacdn.com/tild3362-3231-4934-b162-383333366334/photo.png" alt="Client5"></div>
            <div class="clients-banner"><img src="https://static.tildacdn.com/tild3963-6463-4566-b637-626437316239/photo.png" alt="Client6"></div>
            <div class="clients-banner"><img src="https://static.tildacdn.com/tild3064-3766-4535-a333-376263623732/photo.png" alt="Client7"></div>
        </div>
    </div>
    <footer>
        <div class="footer-container">
            <div class="contact-info">
                <h4>Контакты</h4>
                <p>г. Санкт-Петербург</p>
                <p>+7 921 366 04 32</p>
                <p><a href="mailto:welcome@labi.agency">welcome@labi.agency</a></p>
            </div>
            <div class="privacy-policy">
                <a href="https://kint-print.ru/privacy-policy/" target="_blank">Политика конфиденциальности</a>
            </div>
        </div>
        <div class="ip-info">
            <p>ИНДИВИДУАЛЬНЫЙ ПРЕДПРИНИМАТЕЛЬ БАЛЬЧУГОВ АНДРЕЙ АНДРЕЕВИЧ</p>
            <p>Адрес места жительства (почтовый адрес):</p>
            <p>192177, РОССИЯ, САНКТ-ПЕТЕРБУРГ, УЛ КАРАВАЕВСКАЯ, Д 33, КОРП 5, КВ 14</p>
            <p>ИНН 781137838595</p>
            <p>ОГРНИП 316784700283286</p>
        </div>
        <div class="copyright">
            <p>&copy; AlexLightbringer 2023</p>
        </div>
    </footer>

    <script>
        let slideIndex = 0;
        showSlides();

        function showSlides() {
          let i;
          let slides = document.getElementsByClassName("banner");
          let dots = document.getElementsByClassName("dot");
          for (i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";
          }
          slideIndex++;
          if (slideIndex > slides.length) {slideIndex = 1}
          for (i = 0; i < dots.length; i++) {
            dots[i].className = dots[i].className.replace(" active", "");
          }
          slides[slideIndex-1].style.display = "block";
          dots[slideIndex-1].className += " active";
          setTimeout(showSlides, 2000);
        }
    </script>

{% endblock content %}

home/templates/home/order.html
{% extends "home/base.html" %}

{% block content %}
    <style>
        .form{
            width:35%;
            height:450px;
            background: white;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            padding:20px 30px;
            max-width:calc(100vw - 40px);
            box-sizing:border-box;
            font-family: "Lato", serif;
            position:relative;
            margin-left: auto;
            margin-right: auto;
        }

        .order-title h2{
            margin:10px 0;
            padding-bottom:10px;
            width:180px;
            color: black;
            border-bottom:3px solid #78788c
        }

        input{
            width:100%;
            padding:10px;
            box-sizing:border-box;
            background:none;
            outline:none;
            resize:none;
            border:0;
            font-family: "Lato", serif;
            transition:all .3s;
            border-bottom:2px solid #0c265d
        }

        input:focus{
            border-bottom:2px solid #8a0e0d
        }

        p:before{
            content:attr(type);
            display:block;
            margin:28px 0 0;
            font-size:14px;
            color:#5a5a5a
        }

        .order-btn{
            float:right;
            padding:8px 12px;
            margin-top: 30px;
            font-family: "Lato", serif;
            border:2px solid #8a0e0d;
            background:0;
            color:#8a0e0d;
            cursor:pointer;
            transition:all .3s
        }

        .order-btn:hover{
            background:#8a0e0d;
            color:#fff
        }

        .order-contact{
            position:absolute;
            bottom:-15px;
            right:-20px;
            background:#0c265d;
            color:#fff;
            width:320px;
            padding:16px 4px 16px 0;
            font-size:13px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        }

        .form label{
            width: 100%;
        }

        .fa-envelope-o{
            margin-right: 30px;
        }

        .fa{
            font-family: "Lato", serif;
            padding: 10px;
        }
    </style>
    <form method="post" action="{% url 'home:order' %}" class="form" enctype="multipart/form-data">
        {% csrf_token %}
        <h2 class="order-title">СДЕЛАТЬ ЗАКАЗ</h2>
        <label for="id_name"><input type="text" id="id_name" name="client" placeholder="Ваше имя"></label>
        <label for="id_phone"><input type="text" id="id_phone" name="phone" placeholder="Номер телефона"></label>
        <label for="id_email"><input type="email" id="id_email" name="email" placeholder="Адрес электронной почты"></label>
        <label for="id_text"><input type="text" id="id_text" name="order" placeholder="Комментарий (что желаете заказать и т.д.)"></label>
        <input type="file" id="id_file_upload" name="file_upload">
        <button class="order-btn" type="submit">Отправить заявку</button>
        <div class="order-contact">
            <span class="fa fa-phone">☎ +7 921 366 04 32</span>
            <span class="fa fa-envelope-o">✉ welcome@labi.agency</span>
        </div>
    </form>

{% endblock content %}

home/templates/home/order_complete.html
{% extends "home/base.html" %}
{% block content %}
  <style>
    .complete{
      width:50%;
      background: white;
      box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);;
      box-sizing:border-box;
      font-family: "Lato", serif;
      position:relative;
      margin-left: auto;
      margin-right: auto;
      padding: 20px;
    }
  </style>
<div class="complete">
  <h2>Спасибо!<br>Мы получили Ваш запрос.<br>С Вами скоро свяжется наш менеджер!</h2>
</div>
{% endblock content %}